### ISSUE TITLE
Take care of line breaks

### ISSUE THREAD

**Issue by ruisilva450** [milovidov983/EscapeQuotes#3]
Steps to reproduce:

Have a json file. Eg:
```
{
  "prop0": null,
  "prop1": {
    "inProp1": "value"
  },
  "prop2": null
}
```
Select 
```
           {
    "inProp1": "value"
  }
```
Right click and select Escape quotes
The json comes as:

```
{
  "prop0": null,
  "prop1": prop1\": ,
  "prop2": null
}
```
The expected result:
```
{
  "prop0": null,
  "prop1": {\r\n    \"inProp1\": \"value\"\r\n  },
  "prop2": null
}
```
Again, I know that this is not valid json but this is for me to later add the additional quotes wrapping the escaped bit.

PS: I use [this](https://www.freeformatter.com/json-escape.html) as an example of great handling for this.

BTW, Great job with this extension! Saving a lot of time. 👍

**Comment by milovidov983** [comment]
I see a problem. Apparently the last patch broke multi-line shielding. How will the time I fix it.

**Comment by milovidov983** [comment]
> Steps to reproduce:
> 
> Have a json file. Eg:
> 
> ```
> {
>   "prop0": null,
>   "prop1": {
>     "inProp1": "value"
>   },
>   "prop2": null
> }
> ```
> 
> Select
> 
> ```
>            {
>     "inProp1": "value"
>   }
> ```
> 
> Right click and select Escape quotes
> The json comes as:
> 
> ```
> {
>   "prop0": null,
>   "prop1": prop1\": ,
>   "prop2": null
> }
> ```
> 
> The expected result:
> 
> ```
> {
>   "prop0": null,
>   "prop1": {\r\n    \"inProp1\": \"value\"\r\n  },
>   "prop2": null
> }
> ```
> 
> Again, I know that this is not valid json but this is for me to later add the additional quotes wrapping the escaped bit.
> 
> PS: I use [this](https://www.freeformatter.com/json-escape.html) as an example of great handling for this.
> 
> BTW, Great job with this extension! Saving a lot of time. 👍

I kind of corrected. Please check and write the result.
